### ISSUE TITLE
Application crashes in Navigation menu

### ISSUE THREAD

**Issue by semioticrobotic** [davidgiven/wordgrinder#39] opened 2017-06-12 13:41 UTC
I'm running a test .rpm of WordGrinder that @funnelfiasco [packaged for Fedora 25](https://bugzilla.redhat.com/show_bug.cgi?id=1460246). The application crashes when a user moves swiftly through the Navigation menu.

Steps to reproduce:

1. Press Esc to open main menu
2. Use down arrow to move to last menu item (Navigation)
3. Press Enter
4. Use down arrow to traverse list of navigation options
5. Attempt to scroll past the final menu item
6. Observe crashiness and "lua" gibberish (captured below)

![screenshot from 2017-06-09 18-37-54](https://user-images.githubusercontent.com/19554310/27036587-444bbd5e-4f53-11e7-9709-362ce3ed19b9.png)

**Comment by funnelfiasco** [comment] 2017-06-12 13:44
For what it's worth, I can't reproduce this on my system, which is why I asked Bryan to open an issue here.

**Comment by davidgiven** [comment] 2017-06-12 21:00
This sounds like a corrupt menu structure in the document (yes, the entire menu is stored there).

Any chance you could send me the document you were working on at the time? If you're not happy with attaching it, but are still willing to let me see, let me know and I'll share my GPG public key with you --- I promise to delete it after analysis.

**Comment by semioticrobotic** [comment] 2017-06-13 10:26
Normally I'd be happy to send it along, @davidgiven. But in this case I didn't save it. I do think, though, that I was working with a fresh, unsaved file on both occasions I was able to reproduce the bug. I know that is not as much help as the original file—but perhaps it's something.

**Comment by funnelfiasco** [comment] 2017-06-16 23:40
@semioticrobotic out of curiosity, do you have the `compat-lua-libs` package installed on your system? If you don't, try installing it (`dnf install compat-lua-libs`) and see if that fixes the issue. It wasn't until I was commenting on #38 that I realized I have that package installed, so I may need to tweak the deps (and the build process generally).

**Comment by semioticrobotic** [comment] 2017-06-17 14:20
Thanks, @funnelfiasco. I do indeed have that package installed.

**Comment by davidgiven** [comment] 2017-07-01 16:42
Okay, I've figured out what's going on here.

That error in the stack trace --- "number has no integer representation" --- is something you get from Lua 5.3. It doesn't exist in Lua 5.2 (5.3 changed the way numbers are stored). WordGrinder _does not support_ Lua 5.3 --- it only works with 5.1, LuaJIT, or 5.2.

So what happened here is that the Fedora build process is incorrectly using the wrong Lua library, and then it breaks. That's the packaging bug in #38.

I'm going to close this a WAI, I'm afraid (porting to 5.3 is out of scope for a bug report).

**Comment by davidgiven** [comment] 2017-07-28 20:54
I'm reopening this. Turns out I 'ported' WordGrinder to work with Lua 5.3 a while back, and then forgot I did so, so this is actually supposed to work. Oops, sorry!

**Closed** 2017-07-28 21:28 UTC
