### ISSUE TITLE
Feature Request: Footnotes & endnotes

### ISSUE THREAD

**Issue by iandstanley** [davidgiven/wordgrinder#107] opened 2020-07-22 16:18 UTC
Would it be possible to add footnotes and endnotes to this wonderful word processor? #

**Comment by davidgiven** [comment] 2020-10-07 20:19
Duplicate of #80 

There's already a request for this, so deduplicated there --- I'll comment on that bug...

**Comment by davidgiven** [comment] 2020-10-07 20:19
Duplicate of #80

**Closed by davidgiven** 2020-10-07 20:19 UTC
