### ISSUE TITLE
Feature request: import odt by command line parameter

### ISSUE THREAD

**Issue by rabuzarus** [davidgiven/wordgrinder#70] opened 2019-01-03 11:46 UTC
Please add a parameter which allows to open (import) odt documents from the command line.

By adding this feature, wordgrinder could be used by other programs (eg. mutt) as odt viewer

**Comment by davidgiven** [comment] 2019-01-03 11:53
You can already achieve this, although you need an extra conversion step, using a script like this:

```
WGFILE=/tmp/$$.wg
wordgrinder -convert $ODTFILE $WGFILE
wordgrinder $WGFILE
rm $WGFILE
```

**Comment by rabuzarus** [comment] 2019-01-03 12:57
Thank you. I modified it a little bit to make it work with mutt
`
#!/usr/bin/env sh
#wordgrinder $$
INPUT=$*
ODTFILE=$(basename $*)
WGFILE=/tmp/$ODTFILE.wg
wordgrinder --convert $INPUT $WGFILE
wordgrinder $WGFILE
rm $WGFILE
`

Do you think a separate parameter to import odt documents directly would be useful, or should I close the request?

**Comment by davidgiven** [comment] 2020-10-08 23:37
Very, very belatedly: marking the document dirty on startup is a bug.

Duplicate of #120

**Comment by davidgiven** [comment] 2020-10-08 23:37
Duplicate of #120

**Closed by davidgiven** 2020-10-08 23:37 UTC
