### ISSUE TITLE
System clipboard support

### ISSUE THREAD

**Issue by lproven** [davidgiven/wordgrinder#200] opened 2022-07-22 16:37 UTC
I would like to be able to copy and paste text out of Wordgrinder into other apps, and _vice versa_.

Ideally both by Ctrl+C/V/X and also the Linux middle-click-to-paste support.

**Comment by davidgiven** [comment] 2022-07-26 19:15
Duplicate of #164

**Closed by davidgiven** 2022-07-26 19:15 UTC
